/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



package view;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import model.*;
import controller.*;

/**
 *
 * @author asism
 */
public class LoginView extends javax.swing.JFrame {
    LoginModel model;

    /**
     * Creates new form Login
     */
    public LoginView() {
        initComponents();
    }

        
        
//    LoginButton.addActionListener(new ActionListener() {
//    public void actionPerformed(ActionEvent e) {
//        // Get the values from the text fields
//        String username = UsernameTxtBox.getText();
//        String password = PasswordTxtBox.getText();
//
//        Connection connection = null;
//        try {
//            // Establish connection
//            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/futsaldb","root","#IMUNITED@2002");
//            
//
//            // Check if the username and password match in the database
//            String loginQuery = "SELECT COUNT(*) FROM credentials WHERE username = ? AND pass = ?";
//            PreparedStatement loginStatement = connection.prepareStatement(loginQuery);
//            loginStatement.setString(1, username);
//            loginStatement.setString(2, password);
//            ResultSet resultSet = loginStatement.executeQuery();
//            resultSet.next();
//            int count = resultSet.getInt(1);
//
//            if (count > 0) {
//                System.out.println("Login successful!");
//                // Perform the necessary actions for a successful login
//            } else {
//                System.out.println("Invalid username or password!");
//                // Perform the necessary actions for an unsuccessful login
//            }
//
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//        } finally {
//            // Close the database connection
//            if (connection != null) {
//                try {
//                    connection.close();
//                } catch (SQLException ex) {
//                    ex.printStackTrace();
//                }
//            }
//        }
//    }
//});
//       
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        PasswordTxtBox = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        UsernameTxtBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SignupButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ResetButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(164, 255, 184));

        PasswordTxtBox.setBackground(new java.awt.Color(51, 51, 51));
        PasswordTxtBox.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        PasswordTxtBox.setForeground(new java.awt.Color(255, 255, 255));
        PasswordTxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordTxtBox.setText("Password");
        PasswordTxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmptyonClick(evt);
            }
        });
        PasswordTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTxtBoxActionPerformed(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(51, 153, 255));
        LoginButton.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        UsernameTxtBox.setBackground(new java.awt.Color(51, 51, 51));
        UsernameTxtBox.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        UsernameTxtBox.setForeground(new java.awt.Color(255, 255, 255));
        UsernameTxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UsernameTxtBox.setText("User ID");
        UsernameTxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Emptyonclick(evt);
            }
        });
        UsernameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTxtBoxActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\BEASTMODE\\Documents\\Artboard 2.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\BEASTMODE\\Documents\\Artboard 1.png")); // NOI18N

        jLabel4.setBackground(new java.awt.Color(164, 255, 184));
        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setText("Not Registered Yet? ");

        SignupButton.setBackground(new java.awt.Color(164, 255, 184));
        SignupButton.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        SignupButton.setForeground(new java.awt.Color(0, 102, 204));
        SignupButton.setText("Sign Up");
        SignupButton.setBorder(null);
        SignupButton.setBorderPainted(false);
        SignupButton.setContentAreaFilled(false);
        SignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel5.setText("Now");

        jLabel6.setBackground(new java.awt.Color(164, 255, 184));
        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel6.setText("Forgot Password?");

        ResetButton.setBackground(new java.awt.Color(164, 255, 184));
        ResetButton.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(0, 102, 204));
        ResetButton.setText("Reset");
        ResetButton.setBorder(null);
        ResetButton.setBorderPainted(false);
        ResetButton.setContentAreaFilled(false);
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UsernameTxtBox)
                            .addComponent(PasswordTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(227, 227, 227))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ResetButton))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(56, 56, 56)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(267, 267, 267))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SignupButton)
                            .addComponent(LoginButton))
                        .addGap(304, 304, 304))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(UsernameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(PasswordTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LoginButton)
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignupButton)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetButton))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\BEASTMODE\\Documents\\Artboard 1-100.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTxtBoxActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        LoginController l2 = new LoginController(this);
        
//    String username = UsernameTxtBox.getText();
//    String password = PasswordTxtBox.getText();
//
//    Connection connection = null;
//    try {
//        // Establish connection
//        connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/futsaldb","root","#IMUNITED@2002");
//
//        // Check if the username and password match in the database
//        String loginQuery = "SELECT COUNT(*) FROM credentials WHERE username = ? AND pass = ?";
//        PreparedStatement loginStatement = connection.prepareStatement(loginQuery);
//        loginStatement.setString(1, username);
//        loginStatement.setString(2, password);
//        ResultSet resultSet = loginStatement.executeQuery();
//        resultSet.next();
//        int count = resultSet.getInt(1);
//
//        if (count > 0) {
//            JOptionPane.showMessageDialog(this, "Login successful!");
//            // Perform the necessary actions for a successful login
//        } else {
//            JOptionPane.showMessageDialog(this, "Username or password incorrect!", "Login Failed", JOptionPane.ERROR_MESSAGE);
//            // Perform the necessary actions for an unsuccessful login
//        }
//
//    } catch (SQLException ex) {
//        ex.printStackTrace();
//    } finally {
//        // Close the database connection
//        if (connection != null) {
//            try {
//                connection.close();
//            } catch (SQLException ex) {
//                ex.printStackTrace();
//            }
//        }
//    }

        
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void UsernameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTxtBoxActionPerformed

    private void SignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButtonActionPerformed
        // TODO add your handling code here:
         RegisterView signupForm = new RegisterView();
    signupForm.setVisible(true);
    }//GEN-LAST:event_SignupButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        ResetPassView resetpassForm = new ResetPassView();
        resetpassForm.setVisible(true);
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void Emptyonclick(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Emptyonclick
        // TODO add your handling code here:
        UsernameTxtBox.setText("");
    }//GEN-LAST:event_Emptyonclick

    private void EmptyonClick(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmptyonClick
        // TODO add your handling code here:
        PasswordTxtBox.setText("");
    }//GEN-LAST:event_EmptyonClick

    public LoginModel getUser()
    {
        model = new LoginModel(UsernameTxtBox.getText(), PasswordTxtBox.getText());
        return model;
        
    }
    
    public void setMessage(String msg)
    {
        JOptionPane.showMessageDialog(this,msg);
    }
    
    public void addLoginListner(ActionListener log)
    {
        LoginButton.addActionListener(log);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JTextField PasswordTxtBox;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SignupButton;
    private javax.swing.JTextField UsernameTxtBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
